version: '3.6'


services:
    
   config-server:
      build: ./src/infrastructure/config-server
      container_name: config-server
      volumes:
         - ./src/infrastructure/config-server:/app
      environment:
         SPRING_PROFILES_ACTIVE: prod
      ports:
         - 8888:8888
   
   consul:
    container_name: consul
    ports:
      - "8500:8500"        # Consul UI 
    command: agent -dev -client=0.0.0.0
    environment:
         - CONSUL_BIND_INTERFACE=eth0
   
   api-gateway:
     container_name: api-gateway
     environment:
        ASPNETCORE_ENVIRONMENT: Production
        SPRING__CLOUD__CONFIG__URI: http://config-server:8888
        SPRING__CLOUD__CONFIG__NAME: api-gateway 
        SPRING__CLOUD__CONFIG__PROFILE: prod 
        SPRING__CLOUD__CONFIG__LABEL: master 
     ports:
        - 9500:8080
     depends_on:
        - config-server
        - consul
     
      
