version: '3.6'


services:
   
   config-server:
    image: config-server
    networks:
      - backend_network
   
   consul:
    image: consul:1.15
    networks:
      - backend_network

   api-gateway:
    image: api-gateway:latest
    networks:
      - backend_network

    

networks:
   backend_network:

   
