version: '3.6'


services:
    
    config-server:
       build: ./src/infrastructure/config-server
       container_name: config-server
       volumes:
          - ./src/infrastructure/config-server:/app
       environment:
          SPRING_PROFILES_ACTIVE: prod
       ports:
        - 8889:8888